[project]
name = "codinginterview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pre-commit>=4.1.0",
    "pydantic>=2.11.4",
]
